"""
Scripts Router — The Token Elimination Engine.

Caches deterministic operations as Python scripts. PreToolUse hooks intercept
repeated operations and execute cached scripts with ZERO LLM tokens.

Over a long-running project, this eliminates 60-80% of repetitive tool calls.
Agents generate scripts once; infrastructure runs them forever.
"""

import hashlib
import json
import logging
import os
import subprocess
import sys
import uuid
from pathlib import Path
from fastapi import APIRouter, Request
from pydantic import BaseModel, Field
from typing import Optional

logger = logging.getLogger("archon.scripts")
router = APIRouter()


class RegisterScriptRequest(BaseModel):
    """Register a new cached script for an operation type."""
    operation: str                    # e.g., "parse_json_schema", "extract_file_summary"
    input_shape: str = ""            # JSON shape signature for matching, e.g., "{'file': str}"
    script_content: str              # Python script source code
    description: str = ""


class ExecuteRequest(BaseModel):
    """Execute a cached script by operation match or script ID."""
    operation: Optional[str] = None
    input_shape: Optional[str] = None
    script_id: Optional[str] = None
    input_data: dict = Field(default_factory=dict)


class LookupRequest(BaseModel):
    """Check if a cached script exists for an operation."""
    operation: str
    input_shape: str = ""


# ── Script Registration ─────────────────────────────────────────

@router.post("/register")
async def register_script(req: RegisterScriptRequest, request: Request):
    """Register a Python script for a cacheable operation.
    The script receives JSON on stdin and writes JSON to stdout."""
    kuzu = request.app.state.kuzu
    scripts_path = request.app.state.scripts_path

    # Generate script ID and hash
    script_hash = hashlib.sha256(req.script_content.encode()).hexdigest()[:16]
    script_id = f"script_{req.operation}_{script_hash[:8]}"

    # Write script to disk
    scripts_dir = Path(scripts_path)
    scripts_dir.mkdir(parents=True, exist_ok=True)
    script_path = scripts_dir / f"{script_id}.py"

    # Add standard wrapper for stdin/stdout JSON interface
    wrapped_content = f'''#!/usr/bin/env python3
"""
Cached script: {req.operation}
Description: {req.description}
Input shape: {req.input_shape}
Auto-generated by ARCHON Script Cache.
"""
import json
import sys

def main(input_data):
{_indent(req.script_content, 4)}

if __name__ == "__main__":
    try:
        input_data = json.load(sys.stdin) if not sys.stdin.isatty() else {{}}
        result = main(input_data)
        print(json.dumps(result if result is not None else {{"status": "ok"}}))
    except Exception as e:
        print(json.dumps({{"error": str(e)}}))
        sys.exit(1)
'''
    script_path.write_text(wrapped_content, encoding="utf-8")

    # Register in Kuzu graph
    kuzu.register_script(
        script_id=script_id,
        operation=req.operation,
        input_shape=req.input_shape,
        path=str(script_path),
        script_hash=script_hash,
    )

    # Update registry.json for quick lookup
    registry_path = scripts_dir / "registry.json"
    registry = {}
    if registry_path.exists():
        try:
            registry = json.loads(registry_path.read_text())
        except json.JSONDecodeError:
            registry = {}

    registry[req.operation] = {
        "script_id": script_id,
        "path": str(script_path),
        "input_shape": req.input_shape,
        "hash": script_hash,
        "description": req.description,
    }
    registry_path.write_text(json.dumps(registry, indent=2))

    logger.info(f"Script registered: {script_id} for operation '{req.operation}'")

    return {
        "script_id": script_id,
        "operation": req.operation,
        "path": str(script_path),
        "hash": script_hash,
    }


# ── Script Lookup (for PreToolUse hook) ──────────────────────────

@router.post("/lookup")
async def lookup_script(req: LookupRequest, request: Request):
    """Check if a cached script exists for an operation.
    Called by PreToolUse hook to determine if a tool call can be intercepted."""
    kuzu = request.app.state.kuzu
    result = kuzu.find_cached_script(req.operation, req.input_shape)

    if result:
        # Verify script file still exists on disk
        if Path(result["path"]).exists():
            return {
                "cached": True,
                "script_id": result["id"],
                "path": result["path"],
                "hits": result["hits"],
            }
        else:
            logger.warning(f"Cached script {result['id']} file missing at {result['path']}")

    return {"cached": False, "operation": req.operation}


# ── Script Execution ─────────────────────────────────────────────

@router.post("/execute")
async def execute_script(req: ExecuteRequest, request: Request):
    """Execute a cached script, bypassing LLM inference entirely.
    The script receives input_data as JSON on stdin and returns JSON on stdout."""
    kuzu = request.app.state.kuzu
    redis = request.app.state.redis

    # Find the script
    script_path = None
    script_id = None

    if req.script_id:
        # Direct ID lookup via Kuzu
        scripts_base = request.app.state.scripts_path
        candidate = Path(scripts_base) / f"{req.script_id}.py"
        if candidate.exists():
            script_path = str(candidate)
            script_id = req.script_id

    elif req.operation:
        # Operation-based lookup
        result = kuzu.find_cached_script(req.operation, req.input_shape or "")
        if result and Path(result["path"]).exists():
            script_path = result["path"]
            script_id = result["id"]

    if not script_path:
        return {"executed": False, "error": "No cached script found", "operation": req.operation}

    # Execute the script
    try:
        proc = subprocess.run(
            [sys.executable, script_path],
            input=json.dumps(req.input_data),
            capture_output=True,
            text=True,
            timeout=30,
        )

        if proc.returncode != 0:
            logger.warning(f"Script {script_id} exited with code {proc.returncode}: {proc.stderr}")
            return {
                "executed": True,
                "success": False,
                "script_id": script_id,
                "error": proc.stderr[:500],
                "exit_code": proc.returncode,
            }

        # Parse output
        try:
            output = json.loads(proc.stdout)
        except json.JSONDecodeError:
            output = {"raw_output": proc.stdout[:2000]}

        # Track the cache hit in Redis
        if script_id:
            await redis.track_script_hit(script_id)

        logger.info(f"Script cache hit: {script_id} ({req.operation})")

        return {
            "executed": True,
            "success": True,
            "script_id": script_id,
            "output": output,
            "tokens_saved": "~500-2000",  # Estimated LLM tokens avoided
        }

    except subprocess.TimeoutExpired:
        return {"executed": True, "success": False, "error": "Script timed out (30s)", "script_id": script_id}
    except Exception as e:
        return {"executed": True, "success": False, "error": str(e), "script_id": script_id}


# ── Script Cache Stats ───────────────────────────────────────────

@router.get("/stats")
async def script_stats(request: Request):
    """Get script cache statistics — hits, registered scripts, token savings estimate."""
    redis = request.app.state.redis
    scripts_path = Path(request.app.state.scripts_path)

    redis_stats = await redis.get_script_stats()

    # Count registered scripts
    registry_path = scripts_path / "registry.json"
    registry = {}
    if registry_path.exists():
        try:
            registry = json.loads(registry_path.read_text())
        except json.JSONDecodeError:
            pass

    total_hits = redis_stats.get("total_hits", 0)
    estimated_savings = total_hits * 1000  # ~1000 tokens saved per cache hit

    return {
        "scripts_registered": len(registry),
        "total_cache_hits": total_hits,
        "estimated_tokens_saved": estimated_savings,
        "per_script": redis_stats.get("scripts", []),
        "registry": registry,
    }


@router.get("/list")
async def list_scripts(request: Request):
    """List all registered cached scripts."""
    scripts_path = Path(request.app.state.scripts_path)
    registry_path = scripts_path / "registry.json"

    if registry_path.exists():
        try:
            return json.loads(registry_path.read_text())
        except json.JSONDecodeError:
            pass
    return {}


# ── Helpers ──────────────────────────────────────────────────────

def _indent(code: str, spaces: int) -> str:
    """Indent a block of code by N spaces."""
    prefix = " " * spaces
    lines = code.strip().split("\n")
    return "\n".join(prefix + line for line in lines)
